// Package main demonstrates a minimal gRPC server using the go-wind framework
// with a recovery + logging interceptor chain.
//
// The service definition (message + gRPC stubs) comes from the testing API
// package, so no manual ServiceDesc or protobuf structs are needed here.
//
// Run:
//
//	go run ./grpc-basic
//
// Test with grpcurl:
//
//	grpcurl -plaintext -d '{}' localhost:9000 protobuf.api.HygrothermographService/GetHygrothermograph
package main

import (
	"context"
	"fmt"
	"math/rand"
	"os"
	"os/signal"
	"syscall"

	grpcAPI "github.com/tx7do/go-wind-plugins/testing/api/protobuf"
	"github.com/tx7do/go-wind-plugins/transport/grpc/middleware/logging"
	grpcRecovery "github.com/tx7do/go-wind-plugins/transport/grpc/middleware/recovery"
	grpcServer "github.com/tx7do/go-wind-plugins/transport/grpc/server"
	"google.golang.org/protobuf/types/known/emptypb"
)

// ---------------------------------------------------------------------------
// Hygrothermograph service implementation
// ---------------------------------------------------------------------------

// hygroServiceImpl implements HygrothermographServiceServer generated by protoc.
type hygroServiceImpl struct {
	grpcAPI.UnimplementedHygrothermographServiceServer
}

// GetHygrothermograph returns a random temperature and humidity reading.
func (s *hygroServiceImpl) GetHygrothermograph(_ context.Context, _ *emptypb.Empty) (*grpcAPI.Hygrothermograph, error) {
	return &grpcAPI.Hygrothermograph{
		Humidity:    fmt.Sprintf("%d%%", 40+rand.Intn(40)),
		Temperature: fmt.Sprintf("%.1f°C", 18+rand.Float64()*12),
	}, nil
}

// ---------------------------------------------------------------------------
// main
// ---------------------------------------------------------------------------

func main() {
	srv := grpcServer.NewServer(":9000",
		grpcServer.WithMiddleware(
			grpcRecovery.UnaryInterceptor(),
			logging.UnaryInterceptor(),
		),
	)

	// Register the Hygrothermograph service using the generated registration helper.
	grpcAPI.RegisterHygrothermographServiceServer(srv.Server(), &hygroServiceImpl{})

	// Graceful shutdown.
	ctx, stop := signal.NotifyContext(context.Background(), syscall.SIGINT, syscall.SIGTERM)
	defer stop()

	fmt.Printf("gRPC server listening on %s\n", srv.Endpoint())
	if err := srv.Start(ctx); err != nil {
		fmt.Fprintf(os.Stderr, "server error: %v\n", err)
		os.Exit(1)
	}
	fmt.Println("server stopped")
}
